/**
 * This file is part of the au-log4j package; aka Athabasca University log4j
 * addons.
 * 
 * Copyright Trenton D. Adams <trenton daught d daught adams at gmail daught ca>
 * 
 * au-log4j is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * au-log4j is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public 
 * License along with au-log4j.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * See the COPYING file for more information.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.22 at 09:30:06 AM MDT 
//


package ca.athabascau.util.log4j.xml;

import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for configType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filters" type="{}filterType" maxOccurs="unbounded"
 * minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*@SuppressWarnings("PublicMethodNotExposedInInterface")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configType", propOrder = {
    "filters"})*/
public class ConfigType
{
    protected List filters;

    /**
     * Gets the value of the filters property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the filters property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilters().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list {@link
     * FilterType }
     */
    public List getFilters()
    {
        if (filters == null)
        {
            filters = new ArrayList();
        }
        return this.filters;
    }

    /**
     * Returns a matching filters.  The result may be null if nothing matched.
     *
     * @param logEntry the log entry to match.
     *
     * @return the matching filters or null if nothing matched.
     */
    public FilterType findMatch(final String logEntry)
    {
        getFilters();   // ensure filters is initialized
        for (int index = 0; index < filters.size(); index++)
        {
            final FilterType filter = (FilterType) filters.get(index);
            if (filter.match(logEntry))
            {
                return filter;
            }
        }

        return null;
    }

    /**
     * @param document the xml document
     *
     * @return the ConfigType instance with all appropriate options set.
     */
    public static ConfigType load(final Document document)
    {
        final ConfigType config = new ConfigType();
        final List filters = config.getFilters();
        final NodeList nodeList = document.getElementsByTagName("filter");
        for (int index = 0; index < nodeList.getLength(); index++)
        {
            final Node node = nodeList.item(index);
            filters.add(FilterType.load(node));
        }

        return config;
    }

}
